/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Data.DataSet;
import Data.RawDataSet;
import java.awt.Frame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Amir72c
 */
public class SamplingDebugDialog extends javax.swing.JDialog {

    DataSet myDataSet;
    RawDataSet myRawDataSet;
    
    /**
     * Creates new form SamplingDebugDialog
     */
    public SamplingDebugDialog(java.awt.Frame parent, DataSet dataSet, RawDataSet rawDataSet, boolean modal) {
        super(parent, modal);
        initComponents();
        myDataSet=dataSet;
        myRawDataSet=rawDataSet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        randomSampleButton = new javax.swing.JButton();
        linearSampleButton = new javax.swing.JButton();
        samplePercentSpinner = new javax.swing.JSpinner();
        isFromEndCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        randomSampleButton.setText("Random sample");
        randomSampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomSampleButtonActionPerformed(evt);
            }
        });

        linearSampleButton.setText("Linear sample");
        linearSampleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linearSampleButtonActionPerformed(evt);
            }
        });

        samplePercentSpinner.setModel(new javax.swing.SpinnerNumberModel(30.0d, 0.001d, 99.0d, 1.0d));

        isFromEndCheckBox.setText("From end?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(randomSampleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(samplePercentSpinner))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(linearSampleButton)
                        .addGap(18, 18, 18)
                        .addComponent(isFromEndCheckBox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(randomSampleButton)
                    .addComponent(samplePercentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(linearSampleButton)
                    .addComponent(isFromEndCheckBox))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void randomSampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomSampleButtonActionPerformed
        // TODO add your handling code here:
        CaseDialog caseDialog=new CaseDialog((Frame) SwingUtilities.windowForComponent(this),myDataSet.randomSample(Double.parseDouble(String.valueOf(samplePercentSpinner.getValue()))),true);
        caseDialog.setVisible(true);
    }//GEN-LAST:event_randomSampleButtonActionPerformed

    private void linearSampleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linearSampleButtonActionPerformed
        // TODO add your handling code here:
        CaseDialog caseDialog=new CaseDialog((Frame) SwingUtilities.windowForComponent(this),myDataSet.linearSample(Double.parseDouble(String.valueOf(samplePercentSpinner.getValue())),isFromEndCheckBox.isSelected()),true);
        caseDialog.setVisible(true);
    }//GEN-LAST:event_linearSampleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isFromEndCheckBox;
    private javax.swing.JButton linearSampleButton;
    private javax.swing.JButton randomSampleButton;
    private javax.swing.JSpinner samplePercentSpinner;
    // End of variables declaration//GEN-END:variables
}
