/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphics;

import Data.DataSet;
import MainModel.TestResult;

/**
 *
 * @author Amir72c
 */
public class TestSimpleNetDialog extends javax.swing.JDialog {

    MainFrame myParent;

    /**
     * Creates new form TestSimpleNetDialog
     */
    public TestSimpleNetDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myParent = (MainFrame) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testSimpleNetSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        testPercentSpinner = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        testButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        isRandomDrawnCheckBox = new javax.swing.JCheckBox();
        isSortedByDateCheckBox = new javax.swing.JCheckBox();
        isFromBeginCheckBox = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        testSimpleNetSlider.setMaximum(99);
        testSimpleNetSlider.setMinimum(1);
        testSimpleNetSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                testSimpleNetSliderStateChanged(evt);
            }
        });

        jLabel4.setText("Known transaction percent:");

        testPercentSpinner.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(5.0f), Float.valueOf(1.0f), Float.valueOf(99.0f), Float.valueOf(1.0f)));

        jLabel3.setText("Test percent:");

        jLabel5.setText("50%");

        testButton.setText("Test");
        testButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testButtonActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Sum event error:");

        jLabel2.setText("No test");

        isRandomDrawnCheckBox.setText("Randomly drawn?");
        isRandomDrawnCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isRandomDrawnCheckBoxActionPerformed(evt);
            }
        });

        isSortedByDateCheckBox.setText("Sorted by date?");

        isFromBeginCheckBox.setSelected(true);
        isFromBeginCheckBox.setText("From beginnging?");
        isFromBeginCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isFromBeginCheckBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Sum duration error:");

        jLabel7.setText("No test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(testButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(testPercentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(testSimpleNetSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(isRandomDrawnCheckBox)
                    .addComponent(isSortedByDateCheckBox)
                    .addComponent(isFromBeginCheckBox)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 677, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(testPercentSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isRandomDrawnCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isSortedByDateCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(isFromBeginCheckBox)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testSimpleNetSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void testSimpleNetSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_testSimpleNetSliderStateChanged
        // TODO add your handling code here:
        jLabel5.setText(testSimpleNetSlider.getValue() + "%");
    }//GEN-LAST:event_testSimpleNetSliderStateChanged

    private void testButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testButtonActionPerformed
        // TODO add your handling code here:
        TestResult testResults=null;
        DataSet sampledDataSet;
        if (isRandomDrawnCheckBox.isSelected()) {
            sampledDataSet = myParent.allData.dataSet.randomSample((float) testPercentSpinner.getValue());
            testResults = myParent.allData.simpleNet.testNet(sampledDataSet, testSimpleNetSlider.getValue());
        }else{
            sampledDataSet = myParent.allData.dataSet.linearSample((float) testPercentSpinner.getValue(), !isFromBeginCheckBox.isSelected(),isSortedByDateCheckBox.isSelected());
            testResults = myParent.allData.simpleNet.testNet(sampledDataSet, testSimpleNetSlider.getValue());
        }
        
        jTextArea1.setText(testResults.getRestultsInString());
        jLabel2.setText(String.valueOf(testResults.sumEventError));
        jLabel7.setText(String.valueOf(testResults.sumDurationError));
    }//GEN-LAST:event_testButtonActionPerformed

    private void isFromBeginCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isFromBeginCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isFromBeginCheckBoxActionPerformed

    private void isRandomDrawnCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isRandomDrawnCheckBoxActionPerformed
        // TODO add your handling code here:
        if(isRandomDrawnCheckBox.isSelected())
        {
            isSortedByDateCheckBox.setEnabled(false);
            isFromBeginCheckBox.setEnabled(false);
        }else{
            isSortedByDateCheckBox.setEnabled(true);
            isFromBeginCheckBox.setEnabled(true);
        }
    }//GEN-LAST:event_isRandomDrawnCheckBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox isFromBeginCheckBox;
    private javax.swing.JCheckBox isRandomDrawnCheckBox;
    private javax.swing.JCheckBox isSortedByDateCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton testButton;
    private javax.swing.JSpinner testPercentSpinner;
    private javax.swing.JSlider testSimpleNetSlider;
    // End of variables declaration//GEN-END:variables
}
